export {default as About} from './About/About'
export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as Music} from './Music/Music'
export {default as FormikContact} from './Contact/FormikContact'